#!/usr/bin/bash

set -a;
source env/server.env;

if [[ $# -lt 2 ]] ; then
    echo 'USAGE: copy from.com to.com'
    exit 1
fi

mkdir -p /data01/$2

echo "Copying data from /data01/$1/html to /data01/$2/"
#cp -a /data01/$1/html /data01/$2/

echo "Starting containers"
./start $2

echo "Backing up source"
DOMAIN_NAME=$1 docker-compose -p $1 exec db "mysql_backup"

BACKUP=`ls -t1 /data01/$1/backups/ | head -1` 

echo "Waiting a minute for mysql to finish starting..."
sleep 60

echo "Restoring Database" 
cp -a /data01/$1/backups/$BACKUP /data01/$2/backups/
DOMAIN_NAME=$2 docker-compose -p $2 exec db "bash" -c "zcat /backups/$BACKUP | mysql -p\$MYSQL_ROOT_PASSWORD " 
DOMAIN_NAME=$2 docker-compose -p $2 exec db "bash" -c "mysql -p\$MYSQL_ROOT_PASSWORD -e \"update mysql.user set password=PASSWORD('\$MYSQL_ROOT_PASSWORD') where user='root'; flush privileges;\""

# this is all dumb - remove the <?php
tail -n +2 /data01/$2/html/wp-config.php  > /data01/$2/html/wp-config.php2 
echo -e "<?php\ndefine('WP_HOME','http://$2');\ndefine('WP_SITEURL','http://$2');\n$(cat /data01/$2/html/wp-config.php2)" > /data01/$2/html/wp-config.php2
mv /data01/$2/html/wp-config.php2 /data01/$2/html/wp-config.php

