 version: '2'
 services:
   db:
     image: mariadb:10.1.18
     ports:
       - "3306"
     restart: always
     volumes:
       - /data01/${DOMAIN_NAME}/mysql:/var/lib/mysql
       - /data01/${DOMAIN_NAME}/backups:/backups
       - ./wordpress.cnf:/etc/mysql/conf.d/wordpress.cnf:ro
       - ./mysql_backup:/usr/bin/mysql_backup:ro
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       DOMAIN_NAME: ${DOMAIN_NAME}

   php:
     depends_on:
       - db
     image: wordpress
     links:
       - db
     restart: always
     volumes:
       - /data01/${DOMAIN_NAME}/html:/var/www/html
       - /data01/${DOMAIN_NAME}/cache:/etc/nginx/cache
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
       - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
     #env_file:
     #  - ./${DOMAIN_NAME}.env  

   web:
     image: nginx
     ports:
       - "80"
     volumes:
       - /data01/${DOMAIN_NAME}/html:/var/www/html:ro
       - /data01/${DOMAIN_NAME}/cache:/etc/nginx/cache
       - ./nginx.conf:/etc/nginx/nginx.conf
     links:
       - php
     environment:
       - VIRTUAL_HOST=${DOMAIN_NAMES}
       - HTTPS_METHOD=noredirect
       - LETSENCRYPT_STAGING=1
       - LETSENCRYPT_EMAIL=tripp@wasteoftime.org
     labels:
       - "letsencrypt.nocert=true"
     networks:
       - default
       - nginx-proxy
     restart: always

 networks:
   nginx-proxy:
     external:
       name: nginx-proxy
