 version: '2'
 services:
   db:
     image: mariadb:10.1.18
     restart: always
     volumes:
       - /tmp/${DOMAIN_NAME}/mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   php:
     depends_on:
       - db
     image: wordpress:php7.0-fpm
     links:
       - db
     restart: always
     volumes:
       - /tmp/${DOMAIN_NAME}/html:/var/www/html
       - /tmp/${DOMAIN_NAME}/cache:/etc/nginx/cache
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
       - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_USER: wordpress

   web:
     image: nginx_test
     ports:
       - "80"
     volumes:
       - /tmp/${DOMAIN_NAME}/html:/var/www/html:ro
       - /tmp/${DOMAIN_NAME}/cache:/etc/nginx/cache
       - ./nginx.conf:/etc/nginx/nginx.conf
     links:
       - php
     environment:
       - VIRTUAL_HOST=${DOMAIN_NAME}
       - HTTPS_METHOD=noredirect
       - LETSENCRYPT_STAGING=1
       - LETSENCRYPT_EMAIL=tripp@wasteoftime.org
     networks:
       - default
       - nginx-proxy
     restart: always

 networks:
   nginx-proxy:
     external:
       name: nginx-proxy
