#!/usr/bin/bash

#MYSQL_ROOT_PASSWORD=`openssl rand -base64 32`;
#MYSQL_PASSWORD=`openssl rand -base64 32`;

#echo `echo FrLfgArTcDC7zTTTO9hiomp15EDjLSxpd6n8XciSTb4=$1 | sha256sum | head -c 32`;

#exit;

if [[ $# -eq 0 ]] ; then
    echo 'domain name required'
    exit 1
fi

MYSQL_ROOT_PASSWORD=`echo FrLfgArTcDC7zTTTO9hiomp15EDjLSxpd6n8XciSTb4$1 | sha256sum | head -c 32` \
MYSQL_PASSWORD=`echo o0wlHkuhH0w8eBDOf1pq8490YBurUDaT686Z+YJdmMA$1 | sha256sum | head -c 32` \
DOMAIN_NAME=$1 \
DOMAIN_NAMES=$1,nyc1.$1,www.$1 \
docker-compose -p $1 up -d
